'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        T_n=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      P_n=n(3n-1)/2        1, 5, 12, 22, 35, ...
Hexagonal       H_n=n(2n-1)      1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

answer  = 0
count   = 1
tNums   = [1]
pNums   = [1]
hNums   = [1]
while(answer == 0):
    triNum = count*(count + 1)/2 
    tNums.append(triNum)

    while (triNum > pNums[-1]):
        n = len(pNums) + 1
        pNums.append(n*(3*n - 1)/2)

    while (triNum > hNums[-1]):
        n = len(hNums) + 1
        hNums.append(n*(2*n - 1))

    if triNum in pNums and triNum in hNums and triNum not in [1,40755]:
        answer = triNum

    count += 1

print 'The next triangle number that is also pentagonal and hexagonal is {0}'.format(answer)
